; General configuration 
[Setting]
log_file_path = smith-rs.log
pid_file_path = smith-rs.pid

loadaverage = true
loadaverage_period = 10

memoryusage = true
memoryusage_period = 15

diskusage = true
diskusage_period = 60

ntpdrift = true
ntpdrift_period = 120

[System]
hostname = localhost
load_average_warning_threshold = 16.0
load_average_critical_threshold = 24.0
disks = /, /System/Volumes/Data
disk_warning_threshold = 90
disk_critical_threshold = 95
memory_warning_threshold = 85.0
memory_critical_threshold = 95.0

[Ntp]
ntp_pool_server = pool.ntp.org
ntp_warning_threshold = 1.0
ntp_critical_threshold = 3.0

[Email]
smtp_server = smtp.example.com
smtp_port = 465
sender_email = sender@example.com
receiver_email = receiver@example.com
smtp_username = user
smtp_password = pass

[Alerts]
load = false
memoryusage = false
diskusage = false
ntpdrift = false
